export const Questions = [
  {
    prompt: "Which is of the following is single-threaded ? ",
    optionA: "Java",
    optionB: "Pyton",
    optionC: "Javascript",
    optionD: "C++",
    answer: "C",
  },
  {
    prompt: "Which is best for ML  ? ",
    optionA: "Java",
    optionB: "C#",
    optionC: "Python",
    optionD: "C++",
    answer: "C",
  },
  {
    prompt: "Which of the following is not a react hook ? ",
    optionA: "useEffect",
    optionB: "usecContext",
    optionC: "useSate",
    optionD: "useRetrieve",
    answer: "C",
  },
  {
    prompt: "Which of following is library ? ",
    optionA: "Babel",
    optionB: "Angular",
    optionC: "React.js",
    optionD: "Mojo",
    answer: "C",
  },
  {
    prompt: "What is 2+4 ? ",
    optionA: "1",
    optionB: "4",
    optionC: "6",
    optionD: "2",
    answer: "C",
  },
  {
    prompt: "What is 6+1? ",
    optionA: "24",
    optionB: "4",
    optionC: "7",
    optionD: "2",
    answer: "C",
  },
];
